numero_um=int(input("Insira o primeiro número: "))
numero_dois=int(input("Insira o segundo número: "))
resultado_um=int(numero_um)+(numero_dois)
resultado_dois=int(numero_um)-(numero_dois)
resultado_tres=int(numero_um)*(numero_dois)
resultado_quatro=int(numero_um)/(numero_dois)
print("A soma dos números é de: " +str(resultado_um))
print("A subtração dos números é de: " +str(resultado_dois))
print("A multiplicação dos números é de:" +str(resultado_tres))
print("A divisão dos números é de: " +str(resultado_quatro))
