numero_um=int(input("Insira seu número: "))
numero_dois=int(input("Insira seu número: "))
numero_tres=int(input("Insira seu número: "))
resultado=int(numero_um)+(numero_dois)+(numero_tres)
resultado_1=int(resultado/3)
print("A média aritmética dos números é:" +str(resultado_1))
