numero_um=int(input("insira seu número: "))
resultado_1=int(numero_um-1)
resultado_2=int(numero_um+1)
print("O antecessor do número é: " +str(resultado_1))
print("O sucessor do número é: " +str(resultado_2))
